title: Daniel Vrátil's blog
subtitle: Because opensource matters.
email: me@dvratil.cz
description: >- # this means to ignore newlines until "baseurl:"
  Daniel Vrátil's personal blog.
baseurl: ""
url: "https://dvratil.cz"
twitter_username: danvratil
github_username:  danvratil
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

