title: Daniel Vrátil's blog
subtitle: Because opensource matters.
email: me@dvratil.cz
description: >- # this means to ignore newlines until "baseurl:"
  Daniel Vrátil's personal blog.
baseurl: ""
url: "https://dvratil.cz"
twitter_username: danvratil
github_username:  danvratil


permalink: /:year/:month/:title

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Categories
category_dir: "category"
category_layout: "_layouts/home.html"

taxonomy:
  paginate_root: "/:txtype/:taxon/"
  paginate_path: "page/:num/"

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
    sass_dir: _sass
#    style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
