version: "3.0"

volumes:
  isso:

services:
  isso:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3032:3032"
    networks:
      - net
    restart: always
    volumes:
      - /var/log/isso:/var/log/isso
      - isso:/var/lib/isso

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
