name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all of history for .GitInfo

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        extended: true

    - name: Build
      run: hugo --minify --panicOnWarning

    - uses: actions/upload-artifact@v4
      name: Upload artifact
      with:
        name: public
        path: ${{ github.workspace }}/public/
