name: Deploy

on:
  workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch all history for .GitInfo

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3

    - name: Build
      run: hugo --minify --panicOnWarning

    - name: Deploy to Valhalla
      run: |
        PRIVATE_KEY_FILE=$(mktemp)
        echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > "$PRIVATE_KEY_FILE"
        SSH_CMD="ssh -p ${{ secrets.DEPLOY_PORT }} -i "$PRIVATE_KEY_FILE" -o StrictHostKeyChecking=no"
        rsync -e "$SSH_CMD" -av --delete-after ${{ github.workspace}}/public/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
        rm "$PRIVATE_KEY_FILE"

